// Generated by CoffeeScript 1.3.3
(function() {

  Tactical.Cell = (function() {

    Cell.prototype.size = Tactical.Renderer.prototype.cellSize;

    function Cell(mapX, mapY) {
      this.hover = false;
      this.type = 'empty';
      this.mapX = mapX;
      this.mapY = mapY;
      this.x = 0;
      this.y = 0;
    }

    Cell.prototype.containsPoint = function(pointX, pointY) {
      var inInnerBox, inOuterBox, yIntersect;
      inOuterBox = _([pointX > this.x, pointX < this.x + this.size, pointY > this.y, pointY < this.y + this.size]).all(_.identity);
      if (!inOuterBox) {
        return false;
      }
      inInnerBox = _([pointY > this.y + 0.25 * this.size, pointY < this.y + 0.75 * this.size]).all(_.identity);
      if (inInnerBox) {
        return true;
      }
      if (pointY < this.y + 0.5 * this.size) {
        yIntersect = Math.abs(-(pointX - this.x) / 2 + 0.25 * this.size) + this.y;
        return pointY > yIntersect;
      } else {
        yIntersect = -Math.abs(-(pointX - this.x) / 2 + 0.25 * this.size) + this.size + this.y;
        return pointY < yIntersect;
      }
    };

    return Cell;

  })();

}).call(this);
