// Generated by CoffeeScript 1.3.3
(function() {

  Tactical.DrawingMethods = {
    drawHexagon: function(x, y, s) {
      this.ctx.moveTo(x + s / 2, y);
      this.ctx.beginPath();
      this.ctx.lineTo(x + s, y + s / 4);
      this.ctx.lineTo(x + s, y + (s / 4) * 3);
      this.ctx.lineTo(x + s / 2, y + s);
      this.ctx.lineTo(x, y + (s / 4) * 3);
      this.ctx.lineTo(x, y + s / 4);
      this.ctx.lineTo(x + s / 2, y);
      return this.ctx.closePath();
    },
    strokeHexagon: function(x, y, s) {
      this.drawHexagon(x, y, s);
      return this.ctx.stroke();
    },
    fillHexagon: function(x, y, s) {
      this.drawHexagon(x, y, s);
      return this.ctx.fill();
    },
    clearHexagon: function(x, y, s) {
      this.drawHexagon(x, y, s);
      this.ctx.clip();
      this.clear();
      return this.ctx.restore();
    },
    clear: function() {
      return this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    }
  };

}).call(this);
