// Generated by CoffeeScript 1.3.3
(function() {

  Tactical.Game = (function() {

    function Game(options) {
      if (options == null) {
        options = {};
      }
      _(options).extend({
        selector: '.main',
        playerCount: 5,
        mapWidth: 30,
        mapHeight: 40
      });
      this.$el = $(options.selector);
      this.map = new Tactical.Map(options.mapWidth, options.mapHeight, options.playerCount);
      this.renderer = new Tactical.Renderer(this.map);
      this.$el.html(this.renderer.canvas);
      this.renderer.drawMap();
    }

    Game.prototype._bindUserEvents = function() {
      var _this = this;
      $(this.renderer.canvas).on('mousemove', function(e) {
        var cell, territory;
        e.preventDefault();
        cell = _this.map.cellAtPoint(e.offsetX, e.offsetY);
        if (cell && cell.type !== 'water') {
          cell.hover = true;
        }
        territory = _this.map.territoryForCell(cell);
        if (territory) {
          territory.hover = true;
        }
        _this.renderer.clear();
        _this.renderer.drawMap();
        if (cell) {
          cell.hover = false;
        }
        if (territory) {
          return territory.hover = false;
        }
      });
      return $(this.renderer.canvas).on('click', function(e) {
        var cell;
        e.preventDefault();
        cell = _this.map.cellAtPoint(e.offsetX, e.offsetY);
        if (cell) {
          return console.log(cell);
        }
      });
    };

    return Game;

  })();

}).call(this);
