// Generated by CoffeeScript 1.3.3
(function() {

  Tactical.Player = (function() {

    function Player() {
      var randC;
      randC = function() {
        return Math.floor(Math.random() * 255);
      };
      this.color = "rgb(" + (randC()) + "," + (randC()) + "," + (randC()) + ")";
    }

    return Player;

  })();

}).call(this);
