// Generated by CoffeeScript 1.3.3
(function() {

  Tactical.Territory = (function() {

    function Territory() {
      this.cells = [];
      this.owner = null;
    }

    return Territory;

  })();

}).call(this);
